<?php

namespace TU;

class Tin_can_statement {

  /**
   * $id
   *
   * An ID generated by the LRS to uniquely represent this statement.
   *
   * @var string
   *
   * @access public
   */
  public $id;

  /**
   * $actor
   *
   * An Actor object that is the user for whom this Statement is for.
   *
   * @var Actor
   *
   * @access public
   */
  public $actor;

  /**
   * $verb
   *
   * The Verb object to describe this statement
   *
   * @var Verb
   *
   * @access public
   */
  public $verb;

  /**
   * $object
   *
   * The object that *is* this Statement. Usually an Activity object, but could
   * also be an Actor
   *
   * @var object
   *
   * @access public
   */
  public $object;

  /**
   * $result
   *
   * The object that contains the percentage / mark information
   *
   * @var object
   *
   * @access public
   */
  public $result;

  /**
   * create
   *
   * Send this statement to the LRS.
   * 
   * @access public
   */
  public function create() {
    $response = tu()->tin_can->post('/statements', $this);
    $this->id = $response[0];
  }

}

